# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calibration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calibration.proto',
  package='reactors',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x63\x61libration.proto\x12\x08reactors\"(\n\x11\x43\x61librationStatus\x12\x13\n\x0b\x43\x61librating\x18\x01 \x01(\x08\"\xae\x01\n\x0c\x43heckerboard\x12\x10\n\x08TopLeftx\x18\x01 \x01(\x02\x12\x10\n\x08TopLefty\x18\x02 \x01(\x02\x12\x11\n\tTopRightx\x18\x03 \x01(\x02\x12\x11\n\tTopRighty\x18\x04 \x01(\x02\x12\x13\n\x0b\x42ottomLeftx\x18\x05 \x01(\x02\x12\x13\n\x0b\x42ottomLefty\x18\x06 \x01(\x02\x12\x14\n\x0c\x42ottomRightx\x18\x07 \x01(\x02\x12\x14\n\x0c\x42ottomRighty\x18\x08 \x01(\x02\x62\x06proto3')
)




_CALIBRATIONSTATUS = _descriptor.Descriptor(
  name='CalibrationStatus',
  full_name='reactors.CalibrationStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Calibrating', full_name='reactors.CalibrationStatus.Calibrating', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=71,
)


_CHECKERBOARD = _descriptor.Descriptor(
  name='Checkerboard',
  full_name='reactors.Checkerboard',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='TopLeftx', full_name='reactors.Checkerboard.TopLeftx', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TopLefty', full_name='reactors.Checkerboard.TopLefty', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TopRightx', full_name='reactors.Checkerboard.TopRightx', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TopRighty', full_name='reactors.Checkerboard.TopRighty', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BottomLeftx', full_name='reactors.Checkerboard.BottomLeftx', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BottomLefty', full_name='reactors.Checkerboard.BottomLefty', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BottomRightx', full_name='reactors.Checkerboard.BottomRightx', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BottomRighty', full_name='reactors.Checkerboard.BottomRighty', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=248,
)

DESCRIPTOR.message_types_by_name['CalibrationStatus'] = _CALIBRATIONSTATUS
DESCRIPTOR.message_types_by_name['Checkerboard'] = _CHECKERBOARD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalibrationStatus = _reflection.GeneratedProtocolMessageType('CalibrationStatus', (_message.Message,), dict(
  DESCRIPTOR = _CALIBRATIONSTATUS,
  __module__ = 'calibration_pb2'
  # @@protoc_insertion_point(class_scope:reactors.CalibrationStatus)
  ))
_sym_db.RegisterMessage(CalibrationStatus)

Checkerboard = _reflection.GeneratedProtocolMessageType('Checkerboard', (_message.Message,), dict(
  DESCRIPTOR = _CHECKERBOARD,
  __module__ = 'calibration_pb2'
  # @@protoc_insertion_point(class_scope:reactors.Checkerboard)
  ))
_sym_db.RegisterMessage(Checkerboard)


# @@protoc_insertion_point(module_scope)
