# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kinetics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kinetics.proto',
  package='reactors',
  syntax='proto3',
  serialized_pb=_b('\n\x0ekinetics.proto\x12\x08reactors\"j\n\x0fReactorKinetics\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x10\n\x08pressure\x18\x02 \x01(\x02\x12\r\n\x05label\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\x05\x12\x15\n\rmole_fraction\x18\x05 \x03(\x02\"K\n\x0eSystemKinetics\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12+\n\x08kinetics\x18\x02 \x03(\x0b\x32\x19.reactors.ReactorKineticsB\"\xaa\x02\x1fRochester.Physics.Communicationb\x06proto3')
)




_REACTORKINETICS = _descriptor.Descriptor(
  name='ReactorKinetics',
  full_name='reactors.ReactorKinetics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='reactors.ReactorKinetics.temperature', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pressure', full_name='reactors.ReactorKinetics.pressure', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label', full_name='reactors.ReactorKinetics.label', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='reactors.ReactorKinetics.id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mole_fraction', full_name='reactors.ReactorKinetics.mole_fraction', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=134,
)


_SYSTEMKINETICS = _descriptor.Descriptor(
  name='SystemKinetics',
  full_name='reactors.SystemKinetics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='reactors.SystemKinetics.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kinetics', full_name='reactors.SystemKinetics.kinetics', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=211,
)

_SYSTEMKINETICS.fields_by_name['kinetics'].message_type = _REACTORKINETICS
DESCRIPTOR.message_types_by_name['ReactorKinetics'] = _REACTORKINETICS
DESCRIPTOR.message_types_by_name['SystemKinetics'] = _SYSTEMKINETICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReactorKinetics = _reflection.GeneratedProtocolMessageType('ReactorKinetics', (_message.Message,), dict(
  DESCRIPTOR = _REACTORKINETICS,
  __module__ = 'kinetics_pb2'
  # @@protoc_insertion_point(class_scope:reactors.ReactorKinetics)
  ))
_sym_db.RegisterMessage(ReactorKinetics)

SystemKinetics = _reflection.GeneratedProtocolMessageType('SystemKinetics', (_message.Message,), dict(
  DESCRIPTOR = _SYSTEMKINETICS,
  __module__ = 'kinetics_pb2'
  # @@protoc_insertion_point(class_scope:reactors.SystemKinetics)
  ))
_sym_db.RegisterMessage(SystemKinetics)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\037Rochester.Physics.Communication'))
# @@protoc_insertion_point(module_scope)
