# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GameState.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GameState.proto',
  package='tutorial',
  syntax='proto3',
  serialized_pb=_b('\n\x0fGameState.proto\x12\x08tutorial\"j\n\tAttractor\x12\x10\n\x08position\x18\x01 \x03(\x02\x12(\n\x05state\x18\x02 \x01(\x0e\x32\x19.tutorial.Attractor.State\"!\n\x05State\x12\n\n\x06\x41\x43TIVE\x10\x00\x12\x0c\n\x08INACTIVE\x10\x01\"B\n\tGameState\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\'\n\nattractors\x18\x02 \x03(\x0b\x32\x13.tutorial.AttractorB\"\xaa\x02\x1fRochester.Physics.Communicationb\x06proto3')
)



_ATTRACTOR_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='tutorial.Attractor.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACTIVE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INACTIVE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=102,
  serialized_end=135,
)
_sym_db.RegisterEnumDescriptor(_ATTRACTOR_STATE)


_ATTRACTOR = _descriptor.Descriptor(
  name='Attractor',
  full_name='tutorial.Attractor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='tutorial.Attractor.position', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='tutorial.Attractor.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ATTRACTOR_STATE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=135,
)


_GAMESTATE = _descriptor.Descriptor(
  name='GameState',
  full_name='tutorial.GameState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='tutorial.GameState.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attractors', full_name='tutorial.GameState.attractors', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=203,
)

_ATTRACTOR.fields_by_name['state'].enum_type = _ATTRACTOR_STATE
_ATTRACTOR_STATE.containing_type = _ATTRACTOR
_GAMESTATE.fields_by_name['attractors'].message_type = _ATTRACTOR
DESCRIPTOR.message_types_by_name['Attractor'] = _ATTRACTOR
DESCRIPTOR.message_types_by_name['GameState'] = _GAMESTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Attractor = _reflection.GeneratedProtocolMessageType('Attractor', (_message.Message,), dict(
  DESCRIPTOR = _ATTRACTOR,
  __module__ = 'GameState_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Attractor)
  ))
_sym_db.RegisterMessage(Attractor)

GameState = _reflection.GeneratedProtocolMessageType('GameState', (_message.Message,), dict(
  DESCRIPTOR = _GAMESTATE,
  __module__ = 'GameState_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.GameState)
  ))
_sym_db.RegisterMessage(GameState)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\037Rochester.Physics.Communication'))
# @@protoc_insertion_point(module_scope)
