# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reactors.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='reactors.proto',
  package='reactors',
  syntax='proto3',
  serialized_pb=_b('\n\x0ereactors.proto\x12\x08reactors\"C\n\x07Reactor\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x0e\n\x06xcoord\x18\x03 \x01(\x02\x12\x0e\n\x06ycoord\x18\x04 \x01(\x02\"%\n\x0bReactorPair\x12\n\n\x02r1\x18\x01 \x01(\x05\x12\n\n\x02r2\x18\x02 \x01(\x05\"f\n\rReactorSystem\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\"\n\x07reactor\x18\x02 \x03(\x0b\x32\x11.reactors.Reactor\x12#\n\x04pair\x18\x03 \x03(\x0b\x32\x15.reactors.ReactorPairb\x06proto3')
)




_REACTOR = _descriptor.Descriptor(
  name='Reactor',
  full_name='reactors.Reactor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='reactors.Reactor.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='reactors.Reactor.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xcoord', full_name='reactors.Reactor.xcoord', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ycoord', full_name='reactors.Reactor.ycoord', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=95,
)


_REACTORPAIR = _descriptor.Descriptor(
  name='ReactorPair',
  full_name='reactors.ReactorPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='r1', full_name='reactors.ReactorPair.r1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='r2', full_name='reactors.ReactorPair.r2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=134,
)


_REACTORSYSTEM = _descriptor.Descriptor(
  name='ReactorSystem',
  full_name='reactors.ReactorSystem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='reactors.ReactorSystem.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reactor', full_name='reactors.ReactorSystem.reactor', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pair', full_name='reactors.ReactorSystem.pair', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=238,
)

_REACTORSYSTEM.fields_by_name['reactor'].message_type = _REACTOR
_REACTORSYSTEM.fields_by_name['pair'].message_type = _REACTORPAIR
DESCRIPTOR.message_types_by_name['Reactor'] = _REACTOR
DESCRIPTOR.message_types_by_name['ReactorPair'] = _REACTORPAIR
DESCRIPTOR.message_types_by_name['ReactorSystem'] = _REACTORSYSTEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Reactor = _reflection.GeneratedProtocolMessageType('Reactor', (_message.Message,), dict(
  DESCRIPTOR = _REACTOR,
  __module__ = 'reactors_pb2'
  # @@protoc_insertion_point(class_scope:reactors.Reactor)
  ))
_sym_db.RegisterMessage(Reactor)

ReactorPair = _reflection.GeneratedProtocolMessageType('ReactorPair', (_message.Message,), dict(
  DESCRIPTOR = _REACTORPAIR,
  __module__ = 'reactors_pb2'
  # @@protoc_insertion_point(class_scope:reactors.ReactorPair)
  ))
_sym_db.RegisterMessage(ReactorPair)

ReactorSystem = _reflection.GeneratedProtocolMessageType('ReactorSystem', (_message.Message,), dict(
  DESCRIPTOR = _REACTORSYSTEM,
  __module__ = 'reactors_pb2'
  # @@protoc_insertion_point(class_scope:reactors.ReactorSystem)
  ))
_sym_db.RegisterMessage(ReactorSystem)


# @@protoc_insertion_point(module_scope)
