# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: State.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='State.proto',
  package='communication',
  syntax='proto3',
  serialized_pb=_b('\n\x0bState.proto\x12\rcommunication\"7\n\tStructure\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x10\n\x08position\x18\x03 \x03(\x02\"M\n\x0fStructuresState\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12,\n\nstructures\x18\x02 \x03(\x0b\x32\x18.communication.StructureB\"\xaa\x02\x1fRochester.Physics.Communicationb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_STRUCTURE = _descriptor.Descriptor(
  name='Structure',
  full_name='communication.Structure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='communication.Structure.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='communication.Structure.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='communication.Structure.position', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=85,
)


_STRUCTURESSTATE = _descriptor.Descriptor(
  name='StructuresState',
  full_name='communication.StructuresState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='communication.StructuresState.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='structures', full_name='communication.StructuresState.structures', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=164,
)

_STRUCTURESSTATE.fields_by_name['structures'].message_type = _STRUCTURE
DESCRIPTOR.message_types_by_name['Structure'] = _STRUCTURE
DESCRIPTOR.message_types_by_name['StructuresState'] = _STRUCTURESSTATE

Structure = _reflection.GeneratedProtocolMessageType('Structure', (_message.Message,), dict(
  DESCRIPTOR = _STRUCTURE,
  __module__ = 'State_pb2'
  # @@protoc_insertion_point(class_scope:communication.Structure)
  ))
_sym_db.RegisterMessage(Structure)

StructuresState = _reflection.GeneratedProtocolMessageType('StructuresState', (_message.Message,), dict(
  DESCRIPTOR = _STRUCTURESSTATE,
  __module__ = 'State_pb2'
  # @@protoc_insertion_point(class_scope:communication.StructuresState)
  ))
_sym_db.RegisterMessage(StructuresState)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\037Rochester.Physics.Communication'))
# @@protoc_insertion_point(module_scope)
